# Web Layer Package
# HTTP interface and presentation logic
# Thin controllers that delegate to operations layer

enforce_dependencies: true

dependencies:
  - "."           # Root package (for models like Current, Session, User)
  - app/db        # For direct model access in controllers (sessions)
  - app/operations # For use cases